apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-config
  namespace: lorawan
data:
  chirpstack.toml: |
    [logging]
    level = "info"

    [postgresql]
    dsn = "postgresql://chirpstack:chirpstack_password@postgres.lorawan.svc.cluster.local:5432/chirpstack?sslmode=disable"
    max_open_connections = 10

    [redis]
    servers = [
      "redis://redis.lorawan.svc.cluster.local:6379/0"
    ]

    [network]
    enabled_regions = ["eu868"]

    [api]
    bind = "0.0.0.0:8080"
    secret = "0e7a4b893f12c98d65431201feba98765432109876543210123456789abcdef0"

    [integration]
    enabled = ["mqtt"]

    [integration.mqtt]
    server = "tcp://mosquitto.lorawan.svc.cluster.local:1883"
    json = true

    [gateway]
    client_cert_lifetime = "10y"

  region_eu868.toml: |
    [user_facing_band]
    name = "EU868"

    [regional_parameters]
    id = "eu868"
