apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-mqtt-prefix
  namespace: lorawan
spec:
  stripPrefix:
    prefixes:
      - /mqtt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chirpstack
  namespace: lorawan
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`) && PathPrefix(`/mqtt`)
    middlewares:
    - name: strip-mqtt-prefix
    services:
    - name: mosquitto
      port: ws
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`)
    services:
    - name: chirpstack
      port: 8080
  tls:
    certResolver: myresolver
