apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: lorawan
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: force-wss-headers
  namespace: lorawan
spec:
  headers:
    sslProxyHeaders:
      X-Forwarded-Proto: "https"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Scheme: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "eu1.lorawan.brad.technology"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chirpstack-web
  namespace: lorawan
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`)
    middlewares:
    - name: redirect-to-https
      namespace: lorawan
    services:
    - name: chirpstack
      port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chirpstack-websecure
  namespace: lorawan
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`) && PathPrefix(`/router-info`)
    middlewares:
    - name: force-wss-headers
      namespace: lorawan
    services:
    - name: gateway-bridge
      port: 3001
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`) && PathPrefix(`/router-ns`)
    middlewares:
    - name: force-wss-headers
      namespace: lorawan
    services:
    - name: gateway-bridge
      port: 3001
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`) && PathPrefix(`/gateway`)
    middlewares:
    - name: force-wss-headers
      namespace: lorawan
    services:
    - name: gateway-bridge
      port: 3001
  - kind: Rule
    match: Host(`eu1.lorawan.brad.technology`)
    services:
    - name: chirpstack
      port: 8080
  tls:
    certResolver: myresolver
