apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-bridge
  namespace: lorawan
  labels:
    app: gateway-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-bridge
  template:
    metadata:
      labels:
        app: gateway-bridge
    spec:
      containers:
      - name: gateway-bridge
        image: chirpstack/chirpstack-gateway-bridge:4.0.10
        env:
        - name: GENERAL__LOG_LEVEL
          value: "5"
        - name: BACKEND__TYPE
          value: "basic_station"
        args:
        - -c
        - /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
        ports:
        - containerPort: 3001
          name: lns
          protocol: TCP
        - containerPort: 1700
          name: semtech-udp
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/chirpstack-gateway-bridge
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: gateway-bridge-config
