apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-bridge-config
  namespace: lorawan
data:
  chirpstack-gateway-bridge.toml: |
    [integration.mqtt]
    event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    command_topic_template="eu868/gateway/{{ .GatewayID }}/command/{{ .CommandType }}"

    [integration.mqtt.auth]
    type="generic"

    [integration.mqtt.auth.generic]
    servers=[
      "tcp://mosquitto.lorawan.svc.cluster.local:1883"
    ]

    [backend]
    type="basic_station"

    [backend.basic_station]
    bind="0.0.0.0:3001"
    stats_interval="30s"
    ping_interval="1m0s"
