apiVersion: v1
kind: Service
metadata:
  name: gateway-bridge
  namespace: lorawan
spec:
  type: LoadBalancer
  ports:
  - name: semtech-udp
    port: 1700
    targetPort: 1700
    protocol: UDP
  selector:
    app: gateway-bridge
