apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: gateway-bridge-udp
  namespace: lorawan
spec:
  entryPoints:
  - lorawan-udp
  routes:
  - services:
    - name: gateway-bridge
      port: 1700
