apiVersion: v1
kind: Service
metadata:
  name: gateway-bridge
  namespace: lorawan
spec:
  type: ClusterIP
  ports:
  - name: lns
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: semtech-udp
    port: 1700
    targetPort: 1700
    protocol: UDP
  selector:
    app: gateway-bridge
