apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-bridge-config
  namespace: lorawan
data:
  chirpstack-gateway-bridge.toml: |
    [integration.mqtt]
    event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    command_topic_template="eu868/gateway/{{ .GatewayID }}/command/{{ .CommandType }}"

    [integration.mqtt.auth]
    type="generic"

    [integration.mqtt.auth.generic]
    servers=[
      "tcp://mosquitto.lorawan.svc.cluster.local:1883"
    ]

    [backend.semtech_udp]
    ip="0.0.0.0"
    port=1700
